/**
 * Consumer entry: pulls in core app styles then re-exports the lib bundle.
 * Built assets live in ./publish/ (generated by `npm run build:core-embed` from repo root).
 */
import './publish/slugbase-core-frontend.css';
export { App, createApiClient } from './publish/slugbase-core-frontend.js';
