# Secret Manager secrets. Initial values for jwt/encryption/session must be
# created manually (see docs). DB password is generated and stored here.

resource "google_secret_manager_secret" "jwt_secret" {
  project   = local.project_id
  secret_id = "slugbase-jwt-secret"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret" "encryption_key" {
  project   = local.project_id
  secret_id = "slugbase-encryption-key"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret" "session_secret" {
  project   = local.project_id
  secret_id = "slugbase-session-secret"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}

# Placeholder first versions so Cloud Run can start. Replace with real values in Secret Manager.
resource "random_password" "jwt_placeholder" {
  length  = 48
  special = false
}
resource "google_secret_manager_secret_version" "jwt_secret" {
  secret      = google_secret_manager_secret.jwt_secret.id
  secret_data = random_password.jwt_placeholder.result
}
resource "random_password" "encryption_placeholder" {
  length  = 48
  special = false
}
resource "google_secret_manager_secret_version" "encryption_key" {
  secret      = google_secret_manager_secret.encryption_key.id
  secret_data = random_password.encryption_placeholder.result
}
resource "random_password" "session_placeholder" {
  length  = 48
  special = false
}
resource "google_secret_manager_secret_version" "session_secret" {
  secret      = google_secret_manager_secret.session_secret.id
  secret_data = random_password.session_placeholder.result
}

# DB password: generated by Terraform, stored in Secret Manager and used by Cloud SQL user + Cloud Run
resource "random_password" "db_password" {
  length  = 32
  special = false
}

resource "google_secret_manager_secret" "db_password" {
  project   = local.project_id
  secret_id = "slugbase-db-password"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_password.result
}

# Optional OIDC client secrets (cloud mode). Add a new version with real value when used.
resource "google_secret_manager_secret" "oidc_google_client_secret" {
  project   = local.project_id
  secret_id = "slugbase-oidc-google-client-secret"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}
resource "google_secret_manager_secret_version" "oidc_google_client_secret" {
  secret      = google_secret_manager_secret.oidc_google_client_secret.id
  secret_data = ""
}

resource "google_secret_manager_secret" "oidc_microsoft_client_secret" {
  project   = local.project_id
  secret_id = "slugbase-oidc-microsoft-client-secret"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}
resource "google_secret_manager_secret_version" "oidc_microsoft_client_secret" {
  secret      = google_secret_manager_secret.oidc_microsoft_client_secret.id
  secret_data = ""
}

resource "google_secret_manager_secret" "oidc_github_client_secret" {
  project   = local.project_id
  secret_id = "slugbase-oidc-github-client-secret"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}
resource "google_secret_manager_secret_version" "oidc_github_client_secret" {
  secret      = google_secret_manager_secret.oidc_github_client_secret.id
  secret_data = ""
}

# SMTP password (cloud mode). In cloud mode SMTP is configured via env; only password is secret.
resource "google_secret_manager_secret" "smtp_password" {
  project   = local.project_id
  secret_id = "slugbase-smtp-password"
  replication {
    auto {}
  }
  depends_on = [google_project_service.secretmanager]
}
resource "google_secret_manager_secret_version" "smtp_password" {
  secret      = google_secret_manager_secret.smtp_password.id
  secret_data = ""
}

# Grant runtime SA access to all SlugBase secrets
locals {
  slugbase_secrets = [
    google_secret_manager_secret.jwt_secret.secret_id,
    google_secret_manager_secret.encryption_key.secret_id,
    google_secret_manager_secret.session_secret.secret_id,
    google_secret_manager_secret.db_password.secret_id,
    google_secret_manager_secret.oidc_google_client_secret.secret_id,
    google_secret_manager_secret.oidc_microsoft_client_secret.secret_id,
    google_secret_manager_secret.oidc_github_client_secret.secret_id,
    google_secret_manager_secret.smtp_password.secret_id,
  ]
}

resource "google_secret_manager_secret_iam_member" "runtime_access" {
  for_each  = toset(local.slugbase_secrets)
  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}
